model:
  model_name: 'polarnet_dyco_ray_cluster_with_cls'
  channels: 32
  num_blocks: 7
  semantic_classes: 20
  instance_classes: 18
  sem2ins_classes: []
  semantic_only: False
  semantic_weight: False
  with_coords: True
  ignore_label: -100
  voxel_scale: 50
  use_spp_pool: True
  filter_bg_thresh: 0.1
  iterative_sampling: True
  rays_width: 3
  rays_height: 3
  num_ray_cls: 6

  instance_head_cfg:
    num_dyco_layer: 3
    dec_dim: 128
    #n_sample_pa1: 2048
    #n_queries: 256
    n_sample_pa1: 2048
    n_queries: 256
    radius_scale: 1
    radius: 0.4
    neighbor: 32
  test_cfg:
    x4_split: False
    logit_thresh: 0.0
    score_thresh: 0.2
    npoint_thresh: 100
    type_nms: 'matrix'
    topk: 100

  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']

data:
  train:
    type: 'scannetv2'
    data_root: '/root/src/SoftGroup/dataset/scannetv2'
    #prefix: 'train'
    prefix: 'trainval'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'scannetv2'
    data_root: '/root/src/SoftGroup/dataset/scannetv2'
    prefix: 'val'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    batch_size: 5
    num_workers: 2
  test:
    batch_size: 1
    num_workers: 0

optimizer:
  type: 'AdamW'
  lr: 0.001
  #lr: 0.01
  weight_decay: 0.0001

save_cfg:
  semantic: False
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: False
epochs: 300
step_epoch: 50
save_freq: 4
pretrain: '/root/data/pcdet_data/scannet_pcdet_data/pretrain_scannetv2_val.pth'
#pretrain: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster_cls/epoch_7.pth'
#pretrain: '/root/data/pcdet_models/ISB_model/head_3dyco_scannetv2_val.pth'
work_dir: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster_cls/'

# best weight: pretrains/best_baseline.pth
