model:
  is_mask: False
  model_name: 'polarnet_direct_exp3'
  #model_name: 'polarnet_direct'
  channels: 64
  #channels: 32
  num_blocks: 6
  semantic_classes: 20
  instance_classes: 18
  sem2ins_classes: []
  semantic_only: False
  semantic_weight: False
  with_coords: True
  ignore_label: -100
  voxel_scale: 50
  use_spp_pool: True
  filter_bg_thresh: 0.1
  iterative_sampling: True
  rays_width: 8
  rays_height: 3
  #rays_width: 5
  #rays_height: 5

  instance_head_cfg:
    dec_dim: 256
    n_sample_pa1: 2048
    n_queries: 256
    radius_scale: 1
    radius: 0.4
    neighbor: 32
  test_cfg:
    x4_split: False
    logit_thresh: 0.1
    score_thresh: 0.1
    #score_thresh: 0.3
    npoint_thresh: 100
    type_nms: 'matrix'
    topk: 100

  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']

data:
  train:
    type: 'scannetv2'
    data_root: '/root/src/SoftGroup/dataset/scannetv2'
    prefix: 'train'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'scannetv2'
    data_root: '/root/src/SoftGroup/dataset/scannetv2'
    prefix: 'val'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    #batch_size: 12
    #num_workers: 8
    batch_size: 3
    num_workers: 2
  test:
    #batch_size: 12
    #num_workers: 6
    batch_size: 1
    num_workers: 0

optimizer:
  type: 'AdamW'
  #lr: 0.0005
  lr: 0.1
  weight_decay: 0.00001 #0.0005

save_cfg:
  semantic: False
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: False
epochs: 400
step_epoch: 50
save_freq: 4
pretrain: '/root/data/pcdet_models/ISB_model/with_angles/no_mask/ours/best.pth'
work_dir: '/root/data/pcdet_models/ISB_model/with_angles/no_mask/ours/tune_exp/'

# best weight: pretrains/best_baseline.pth
