model:
  model_name: 'polarnet_dyco_ray_cluster_gamma_ablation'
  channels: 32
  num_blocks: 7
  semantic_classes: 13
  instance_classes: 11
  sem2ins_classes: [0,1]
  semantic_only: False
  semantic_weight: False
  with_coords: True
  ignore_label: -100
  voxel_scale: 50
  use_spp_pool: True
  filter_bg_thresh: 0.4
  iterative_sampling: True
  rays_width: 3
  rays_height: 3
  #rays_width: 5
  #rays_height: 5
  activation: ['ray','gamma_clustering','2nd_refine']

  instance_head_cfg:
    dec_dim: 128
    num_dyco_layer: 3
    #n_sample_pa1: 2048
    #n_queries: 256
    n_sample_pa1: 2048
    #n_queries: 256
    n_queries: 256
    radius_scale: 1
    radius: 0.4
    neighbor: 32
  test_cfg:
    x4_split: True
    logit_thresh: 0.0
    score_thresh: 0.5
    #score_thresh: 0.01
    npoint_thresh: 400
    type_nms: 'standard'
    topk: -1 #200 #1000 #500
    nms_threshold: 0.2
  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']

data:
  train:
    type: 's3dis'
    data_root: 'dataset/s3dis/'
    prefix: ['Area_1', 'Area_3', 'Area_4', 'Area_5', 'Area_6']
    #prefix: 'trainval'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 20
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 's3dis'
    data_root: 'dataset/s3dis/'
    prefix: 'Area_2'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    batch_size: 10
    num_workers: 10
    
  test:
    batch_size: 1
    num_workers: 0

optimizer:
  type: 'AdamW'
  lr: 0.001
  #lr: 0.01
  weight_decay: 0.00001

save_cfg:
  semantic: False
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: False
epochs: 100
step_epoch: 20
save_freq: 4
paper: True
#work_dir: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster' #ori

#pretrain: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster_gamma_ablation/ray_gamma_refine_paper/paper_result.pth'
#pretrain: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster_gamma_ablation/ray_gamma_refine_margin/epoch_206.pth'
#pretrain: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster_gamma_ablation/ray_gamma_refine_paper_more_train/epoch_180.pth'
#work_dir: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster_gamma_ablation/ray_gamma_refine_margin/'

pretrain: '/root/data/pcdet_models/ISB_model_s3dis/dyco_rays_cluster/epoch_40.pth' #paper for test
work_dir: '/root/data/pcdet_models/ours_s3dis_area2/'
#work_dir: '/root/data/pcdet_models/ISB_model/dyco_rays_cluster_gamma_ablation/ray_gamma_refine_paper_more_train/'
# best weight: pretrains/best_baseline.pth
