model:
  model_name: 'polarnet_dyco_ray_cluster'
  channels: 32
  num_blocks: 7
  semantic_classes: 13
  instance_classes: 11
  sem2ins_classes: [0,1]
  semantic_only: False
  semantic_weight: False
  with_coords: True
  ignore_label: -100
  voxel_scale: 50
  use_spp_pool: True
  filter_bg_thresh: 0.4
  iterative_sampling: True
  rays_width: 8
  rays_height: 3

  instance_head_cfg:
    num_dyco_layer: 2
    dec_dim: 128
    n_sample_pa1: 2048
    n_queries: 256
    radius_scale: 1
    radius: 0.4
    neighbor: 32
  test_cfg:
    x4_split: True
    logit_thresh: 0.0
    score_thresh: 0.5
    npoint_thresh: 400
    type_nms: 'standard'
    topk: -1
    nms_threshold: 0.2

  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']

data:
  train:
    type: 's3dis'
    data_root: 'dataset/s3dis/'
    prefix: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
    #prefix: 'trainval'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 20
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 's3dis'
    data_root: 'dataset/s3dis/'
    prefix: 'Area_5'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    batch_size: 10
    num_workers: 10
  test:
    batch_size: 1
    num_workers: 0

optimizer:
  type: 'AdamW'
  lr: 0.001
  #lr: 0.01
  weight_decay: 0.0001

save_cfg:
  semantic: False
  offset: False
  instance: True
  offset_vertices: False
  nmc_clusters: False
  object_conditions: False

fp16: False
epochs: 300
step_epoch: 40
save_freq: 4
#pretrain: '/root/data/pcdet_data/scannet_pcdet_data/pretrain_scannetv2_val.pth'
#pretrain: '/root/data/pcdet_models/ISB_model/head_3dyco_scannetv2_val.pth'
#pretrain: '/root/data/pcdet_data/scannet200/pretrain_scannetv2_200_val.pth'
#pretrain: '/root/data/pcdet_data/s3dis/pretrain_s3dis_area5.pth'
#pretrain: '/root/data/pcdet_models/s3dis/epoch_59.pth'
#pretrain: '/root/data/pcdet_models/s3dis/epoch_40.pth'
#pretrain: '/root/data/pcdet_models/ISB_model_s3dis/dyco_rays_cluster/epoch_43.pth' #paper
pretrain: '/root/data/pcdet_models/ISB_model_s3dis/dyco_rays_cluster/epoch_40.pth' #paper for test
work_dir: '/root/data/pcdet_models/ISB_model_s3dis/dyco_rays_cluster'

# best weight: pretrains/best_baseline.pth
